/*
 * Copyright 2020 The edap Project
 *
 * The Netty Project licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

package io.edap.data.jdbc;

import io.edap.log.Logger;
import io.edap.log.LoggerManager;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;

public class SingleStatementSession implements StatementSession {

    static Logger LOG = LoggerManager.getLogger(SingleStatementSession.class);

    private Connection con;

    /**
     * 当前 {@link #con} 是否是 tx 共享 con。
     * 在 {@link #getConnection()} 返回的瞬间由 {@link ConnectionHolder#isInTransaction()}
     * 记录,用于 {@link #close(boolean)} 判断 session 自己是否可以 close con:
     * <ul>
     *   <li>true —— con 是 tx 共享 con,生命周期由 tx manager 负责,session 不能 close</li>
     *   <li>false —— con 是 session 独占 con,session 需要自己 close 归还 ds</li>
     * </ul>
     * 在 getConnection 时刻记录(不在 close 时判定),防止 session 跨 tx 边界
     * 持有导致误关共享 con。
     */
    private boolean conIsShared;

    private ConnectionHolder conHolder;

    //private Map<String, PreparedStatement> preparedStmts = new HashMap<>();


    @Override
    public ConnectionHolder getConHolder() {
        return conHolder;
    }

    @Override
    public void setConHolder(ConnectionHolder conHolder) {
        this.conHolder = conHolder;
    }

    private Connection getConnection() throws SQLException {
        if (con == null || con.isClosed()) {
            con = conHolder.getConnection();
            // 在拿到 con 的同一调用栈里记录"是否 tx 共享 con" —— 后续 close 时用来
            // 判断 session 自己是否可以关 con。TxConnectionHolder 会在 TxScope.currentStatus()
            // 不为 null 时返回 true(共享 con,生命周期归 tx manager);非 tx 路径返回 false
            // (con 是 session 独占,需要 session 自己 close 归还 ds,否则 con 泄漏)。
            conIsShared = conHolder.isInTransaction();
        }
        return con;
    }

    @Override
    public Statement createStatement() throws SQLException {
        Connection con = getConnection();
        return con.createStatement();
    }

    @Override
    public boolean getAutoCommit() throws SQLException {
        Connection con = getConnection();
        return con.getAutoCommit();
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
//        PreparedStatement pstmt = preparedStmts.get(sql);
//        if (pstmt == null || pstmt.getConnection() == null || pstmt.getConnection().isClosed()) {
//            Connection con = getConnection();
//            pstmt = con.prepareStatement(sql);
//            preparedStmts.put(sql, pstmt);
//        }
        return getConnection().prepareStatement(sql);
        //return getConnection().prepareStatement(sql);
    }

    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
//        String key = sql + "_" + autoGeneratedKeys;
//        PreparedStatement pstmt = preparedStmts.get(key);
//        if (pstmt == null) {
//            Connection con = getConnection();
//            pstmt = con.prepareStatement(sql, autoGeneratedKeys);
//            preparedStmts.put(key, pstmt);
//        }
        return getConnection().prepareStatement(sql, autoGeneratedKeys);
    }

    @Override
    public void close() {
        boolean isAutoCommit = true;
        try {
            isAutoCommit = getAutoCommit();
        } catch (SQLException e) {
            LOG.warn("getAutoCommit error", e);
        }
        close(isAutoCommit);
    }

    public void closePreparedStatement(PreparedStatement pstmt) {
        try {
            pstmt.close();
        } catch (Throwable e) {
            LOG.warn("PreparedStatement close error", e);
        }
    }

    @Override
    public void close(boolean closeConnection) {
        try {
            if (closeConnection) {
                conHolder.releaseConnection();
                // 兜底:非 tx 路径(独占 con)下 conHolder 是 TxConnectionHolder 时
                // releaseConnection() no-op,con 不会被归还 HikariCP。需要 session
                // 自己 close 归还 ds —— 否则 con 泄漏 → 池涨 → PG "too many clients"
                // (ESTYLR 2026-09-06 反馈:"没有事务的时候,没有机会关闭连接了")
                // tx 路径(共享 con)下 conIsShared=true,跳过本分支,避免误关共享 con
                // (ESTYLR 2026-09-05 事故根因)。
                if (con != null && !conIsShared && !con.isClosed()) {
                    try {
                        con.close();
                    } catch (SQLException e) {
                        LOG.warn("SingleStatementSession close con error", e);
                    }
                }
            }
        } catch (Throwable e) {
            LOG.warn("SingleStatementSession close error", e);
        } finally {
            this.con = null;
            this.conIsShared = false;
        }
    }

    @Override
    public void commit() throws SQLException {
        Connection con = getConnection();
        if (con != null) {
            con.commit();
        }
    }

    @Override
    public void rollback() throws SQLException {
        Connection con = getConnection();
        if (con != null) {
            con.rollback();
        }
    }
}
