/*
 * Copyright 2020 The edap Project
 *
 * The Netty Project licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

package io.edap.data.jdbc;

import io.edap.log.Logger;
import io.edap.log.LoggerManager;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;

public class SingleStatementSession implements StatementSession {

    static Logger LOG = LoggerManager.getLogger(SingleStatementSession.class);

    private Connection con;

    private ConnectionHolder conHolder;

    //private Map<String, PreparedStatement> preparedStmts = new HashMap<>();


    @Override
    public ConnectionHolder getConHolder() {
        return conHolder;
    }

    @Override
    public void setConHolder(ConnectionHolder conHolder) {
        this.conHolder = conHolder;
    }

    private Connection getConnection() throws SQLException {
        if (con == null || con.isClosed()) {
            con = conHolder.getConnection();
        }
        return con;
    }

    @Override
    public Statement createStatement() throws SQLException {
        Connection con = getConnection();
        return con.createStatement();
    }

    @Override
    public boolean getAutoCommit() throws SQLException {
        Connection con = getConnection();
        return con.getAutoCommit();
    }

    @Override
    public void setAutoCommit(boolean autoCommit) throws SQLException {
        Connection con = getConnection();
        con.setAutoCommit(autoCommit);
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
//        PreparedStatement pstmt = preparedStmts.get(sql);
//        if (pstmt == null || pstmt.getConnection() == null || pstmt.getConnection().isClosed()) {
//            Connection con = getConnection();
//            pstmt = con.prepareStatement(sql);
//            preparedStmts.put(sql, pstmt);
//        }
        return getConnection().prepareStatement(sql);
        //return getConnection().prepareStatement(sql);
    }

    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
//        String key = sql + "_" + autoGeneratedKeys;
//        PreparedStatement pstmt = preparedStmts.get(key);
//        if (pstmt == null) {
//            Connection con = getConnection();
//            pstmt = con.prepareStatement(sql, autoGeneratedKeys);
//            preparedStmts.put(key, pstmt);
//        }
        return getConnection().prepareStatement(sql, autoGeneratedKeys);
    }

    @Override
    public void close() {
        boolean isAutoCommit = true;
        try {
            isAutoCommit = getAutoCommit();
        } catch (SQLException e) {
            LOG.warn("getAutoCommit error", e);
        }
        close(isAutoCommit);
    }

    public void closePreparedStatement(PreparedStatement pstmt) {
        try {
            pstmt.close();
        } catch (Throwable e) {
            LOG.warn("PreparedStatement close error", e);
        }
    }

    @Override
    public void close(boolean closeConnection) {
        try {
            if (closeConnection) {
                conHolder.releaseConnection();
            }
        } catch (Throwable e) {
            LOG.warn("SingleStatementSession close error", e);
        } finally {
            // 关闭本 session 持有的 con —— {@code TxConnectionHolder} 已不再缓存 con,
            // releaseConnection() 是 no-op,所以这里必须自己关,否则连接泄漏到池外。
            // 与 {@code SimpleConnectionHolder} 共存时,会出现"先 close con 再 close conHolder 的缓存"
            // —— driver 的 close() 普遍幂等(HikariCP / PG 均用 closed 标志做幂等),
            // setAutoCommit(true) 对已关闭 con 会抛 SQLException,这里吞掉即可。
            Connection localCon = this.con;
            if (localCon != null) {
                try {
                    localCon.setAutoCommit(true);
                } catch (SQLException ignore) {
                    // 还原失败不影响 close —— 模式参照 JdbcTransactionResource#releaseConnection
                }
                try {
                    localCon.close();
                } catch (SQLException ignore) {
                    // 同上
                }
                this.con = null;
            }
        }
    }

    @Override
    public void commit() throws SQLException {
        Connection con = getConnection();
        if (con != null) {
            con.commit();
        }
    }

    @Override
    public void rollback() throws SQLException {
        Connection con = getConnection();
        if (con != null) {
            con.rollback();
        }
    }
}
