package io.edap.mqtt;

import static io.edap.mqtt.PacketProperty.*;

public enum PropertyType {

    PAYLOAD_FORMAT_INDICATOR          (PAYLOAD_FORMAT_INDICATOR_ID),
    MESSAGE_EXPIRY_INTERVAL           (MESSAGE_EXPIRY_INTERVAL_ID),
    CONTENT_TYPE                      (CONTENT_TYPE_ID),
    RESPONSE_TOPIC                    (RESPONSE_TOPIC_ID),
    CORRELATION_DATA                  (CORRELATION_DATA_ID),
    SUBSCRIPTION_INDENTIFIER          (SUBSCRIPTION_INDENTIFIER_ID),
    SESSION_EXPIRY_INTERVAL           (SESSION_EXPIRY_INTERVAL_ID),
    ASSIGNED_CLIENT_IDENTIFIER        (ASSIGNED_CLIENT_IDENTIFIER_ID),
    SERVER_KEEP_ALIVE                 (SERVER_KEEP_ALIVE_ID),
    AUTHENTICATION_METHOD             (AUTHENTICATION_METHOD_ID),
    AUTHENTICATION_DATA               (AUTHENTICATION_DATA_ID),
    REQUEST_PROBLEM_INFORMATION       (REQUEST_PROBLEM_INFORMATION_ID),
    WILL_DELAY_INTERVAL               (WILL_DELAY_INTERVAL_ID),
    REQUEST_RESPONSE_INFORMATION      (REQUEST_RESPONSE_INFORMATION_ID),
    RESPONSE_INFORMATION              (RESPONSE_INFORMATION_ID),
    SERVER_REFERENCE                  (SERVER_REFERENCE_ID),
    REASON_STRING                     (REASON_STRING_ID),
    RECEIVE_MAXINUM                   (RECEIVE_MAXINUM_ID),
    TOPIC_ALIAS_MAXIMUM               (TOPIC_ALIAS_MAXIMUM_ID),
    TOPIC_ALIAS                       (TOPIC_ALIAS_ID),
    MAXIMUM_QOS                       (MAXIMUM_QOS_ID),
    RETAIN_AVAILABLE                  (RETAIN_AVAILABLE_ID),
    USER_PROPERTY                     (USER_PROPERTY_ID),
    MAXIMUM_PACKET_SIZE               (MAXIMUM_PACKET_SIZE_ID),
    WILDCARD_SUBSCRIPTION_AVAILABLE   (WILDCARD_SUBSCRIPTION_AVAILABLE_ID),
    SUBSCRIPTION_INDENTIFIER_AVAILABLE(SUBSCRIPTION_INDENTIFIER_AVAILABLE_ID),
    SHARED_SUBSCRIPTION_AVAILABLE     (SHARED_SUBSCRIPTION_AVAILABLE_ID);

    private int type;

    PropertyType(int type) {
        this.type = type;
    }

    public int getType() {
        return type;
    }
}
