// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: list_float.proto
// Protobuf Java Version: 4.29.3

package io.edap.protobuf.test.message.v3;

public final class ListFloatOuterClass {
  private ListFloatOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ListFloatOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ListFloatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.message.ListFloat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated float f = 1;</code>
     * @return A list containing the f.
     */
    java.util.List<java.lang.Float> getFList();
    /**
     * <code>repeated float f = 1;</code>
     * @return The count of f.
     */
    int getFCount();
    /**
     * <code>repeated float f = 1;</code>
     * @param index The index of the element to return.
     * @return The f at the given index.
     */
    float getF(int index);
  }
  /**
   * Protobuf type {@code test.message.ListFloat}
   */
  public static final class ListFloat extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:test.message.ListFloat)
      ListFloatOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ListFloat.class.getName());
    }
    // Use ListFloat.newBuilder() to construct.
    private ListFloat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ListFloat() {
      f_ = emptyFloatList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.edap.protobuf.test.message.v3.ListFloatOuterClass.internal_static_test_message_ListFloat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.edap.protobuf.test.message.v3.ListFloatOuterClass.internal_static_test_message_ListFloat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat.class, io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat.Builder.class);
    }

    public static final int F_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.FloatList f_ =
        emptyFloatList();
    /**
     * <code>repeated float f = 1;</code>
     * @return A list containing the f.
     */
    @java.lang.Override
    public java.util.List<java.lang.Float>
        getFList() {
      return f_;
    }
    /**
     * <code>repeated float f = 1;</code>
     * @return The count of f.
     */
    public int getFCount() {
      return f_.size();
    }
    /**
     * <code>repeated float f = 1;</code>
     * @param index The index of the element to return.
     * @return The f at the given index.
     */
    public float getF(int index) {
      return f_.getFloat(index);
    }
    private int fMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getFList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(fMemoizedSerializedSize);
      }
      for (int i = 0; i < f_.size(); i++) {
        output.writeFloatNoTag(f_.getFloat(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getFList().size();
        size += dataSize;
        if (!getFList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        fMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat)) {
        return super.equals(obj);
      }
      io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat other = (io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat) obj;

      if (!getFList()
          .equals(other.getFList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getFCount() > 0) {
        hash = (37 * hash) + F_FIELD_NUMBER;
        hash = (53 * hash) + getFList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.message.ListFloat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.message.ListFloat)
        io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.edap.protobuf.test.message.v3.ListFloatOuterClass.internal_static_test_message_ListFloat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.edap.protobuf.test.message.v3.ListFloatOuterClass.internal_static_test_message_ListFloat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat.class, io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat.Builder.class);
      }

      // Construct using io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        f_ = emptyFloatList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.edap.protobuf.test.message.v3.ListFloatOuterClass.internal_static_test_message_ListFloat_descriptor;
      }

      @java.lang.Override
      public io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat getDefaultInstanceForType() {
        return io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat.getDefaultInstance();
      }

      @java.lang.Override
      public io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat build() {
        io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat buildPartial() {
        io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat result = new io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          f_.makeImmutable();
          result.f_ = f_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat) {
          return mergeFrom((io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat other) {
        if (other == io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat.getDefaultInstance()) return this;
        if (!other.f_.isEmpty()) {
          if (f_.isEmpty()) {
            f_ = other.f_;
            f_.makeImmutable();
            bitField0_ |= 0x00000001;
          } else {
            ensureFIsMutable();
            f_.addAll(other.f_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                float v = input.readFloat();
                ensureFIsMutable();
                f_.addFloat(v);
                break;
              } // case 13
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                int alloc = length > 4096 ? 4096 : length;
                ensureFIsMutable(alloc / 4);
                while (input.getBytesUntilLimit() > 0) {
                  f_.addFloat(input.readFloat());
                }
                input.popLimit(limit);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.FloatList f_ = emptyFloatList();
      private void ensureFIsMutable() {
        if (!f_.isModifiable()) {
          f_ = makeMutableCopy(f_);
        }
        bitField0_ |= 0x00000001;
      }
      private void ensureFIsMutable(int capacity) {
        if (!f_.isModifiable()) {
          f_ = makeMutableCopy(f_, capacity);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated float f = 1;</code>
       * @return A list containing the f.
       */
      public java.util.List<java.lang.Float>
          getFList() {
        f_.makeImmutable();
        return f_;
      }
      /**
       * <code>repeated float f = 1;</code>
       * @return The count of f.
       */
      public int getFCount() {
        return f_.size();
      }
      /**
       * <code>repeated float f = 1;</code>
       * @param index The index of the element to return.
       * @return The f at the given index.
       */
      public float getF(int index) {
        return f_.getFloat(index);
      }
      /**
       * <code>repeated float f = 1;</code>
       * @param index The index to set the value at.
       * @param value The f to set.
       * @return This builder for chaining.
       */
      public Builder setF(
          int index, float value) {

        ensureFIsMutable();
        f_.setFloat(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated float f = 1;</code>
       * @param value The f to add.
       * @return This builder for chaining.
       */
      public Builder addF(float value) {

        ensureFIsMutable();
        f_.addFloat(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated float f = 1;</code>
       * @param values The f to add.
       * @return This builder for chaining.
       */
      public Builder addAllF(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureFIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, f_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated float f = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearF() {
        f_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:test.message.ListFloat)
    }

    // @@protoc_insertion_point(class_scope:test.message.ListFloat)
    private static final io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat();
    }

    public static io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ListFloat>
        PARSER = new com.google.protobuf.AbstractParser<ListFloat>() {
      @java.lang.Override
      public ListFloat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ListFloat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListFloat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.edap.protobuf.test.message.v3.ListFloatOuterClass.ListFloat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_message_ListFloat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_message_ListFloat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020list_float.proto\022\014test.message\"\026\n\tList" +
      "Float\022\t\n\001f\030\001 \003(\002B\"\n io.edap.protobuf.tes" +
      "t.message.v3b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_test_message_ListFloat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_message_ListFloat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_test_message_ListFloat_descriptor,
        new java.lang.String[] { "F", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
