// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: one_enum.proto

package io.edap.protobuf.test.message.v3;

public final class OneEnumOuterClass {
  private OneEnumOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code test.message.Corpus}
   */
  public enum Corpus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNIVERSAL = 0;</code>
     */
    UNIVERSAL(0),
    /**
     * <code>WEB = 1;</code>
     */
    WEB(1),
    /**
     * <code>IMAGES = 2;</code>
     */
    IMAGES(2),
    /**
     * <code>LOCAL = 3;</code>
     */
    LOCAL(3),
    /**
     * <code>NEWS = 4;</code>
     */
    NEWS(4),
    /**
     * <code>PRODUCTS = 5;</code>
     */
    PRODUCTS(5),
    /**
     * <code>VIDEO = 6;</code>
     */
    VIDEO(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNIVERSAL = 0;</code>
     */
    public static final int UNIVERSAL_VALUE = 0;
    /**
     * <code>WEB = 1;</code>
     */
    public static final int WEB_VALUE = 1;
    /**
     * <code>IMAGES = 2;</code>
     */
    public static final int IMAGES_VALUE = 2;
    /**
     * <code>LOCAL = 3;</code>
     */
    public static final int LOCAL_VALUE = 3;
    /**
     * <code>NEWS = 4;</code>
     */
    public static final int NEWS_VALUE = 4;
    /**
     * <code>PRODUCTS = 5;</code>
     */
    public static final int PRODUCTS_VALUE = 5;
    /**
     * <code>VIDEO = 6;</code>
     */
    public static final int VIDEO_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Corpus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Corpus forNumber(int value) {
      switch (value) {
        case 0: return UNIVERSAL;
        case 1: return WEB;
        case 2: return IMAGES;
        case 3: return LOCAL;
        case 4: return NEWS;
        case 5: return PRODUCTS;
        case 6: return VIDEO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Corpus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Corpus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Corpus>() {
            public Corpus findValueByNumber(int number) {
              return Corpus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.edap.protobuf.test.message.v3.OneEnumOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final Corpus[] VALUES = values();

    public static Corpus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Corpus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:test.message.Corpus)
  }

  public interface OneEnumOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.message.OneEnum)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.test.message.Corpus corpus = 1;</code>
     * @return The enum numeric value on the wire for corpus.
     */
    int getCorpusValue();
    /**
     * <code>.test.message.Corpus corpus = 1;</code>
     * @return The corpus.
     */
    io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus getCorpus();
  }
  /**
   * Protobuf type {@code test.message.OneEnum}
   */
  public  static final class OneEnum extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:test.message.OneEnum)
      OneEnumOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OneEnum.newBuilder() to construct.
    private OneEnum(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OneEnum() {
      corpus_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OneEnum();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OneEnum(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              corpus_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.edap.protobuf.test.message.v3.OneEnumOuterClass.internal_static_test_message_OneEnum_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.edap.protobuf.test.message.v3.OneEnumOuterClass.internal_static_test_message_OneEnum_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum.class, io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum.Builder.class);
    }

    public static final int CORPUS_FIELD_NUMBER = 1;
    private int corpus_;
    /**
     * <code>.test.message.Corpus corpus = 1;</code>
     * @return The enum numeric value on the wire for corpus.
     */
    public int getCorpusValue() {
      return corpus_;
    }
    /**
     * <code>.test.message.Corpus corpus = 1;</code>
     * @return The corpus.
     */
    public io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus getCorpus() {
      @SuppressWarnings("deprecation")
      io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus result = io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus.valueOf(corpus_);
      return result == null ? io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (corpus_ != io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus.UNIVERSAL.getNumber()) {
        output.writeEnum(1, corpus_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (corpus_ != io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus.UNIVERSAL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, corpus_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum)) {
        return super.equals(obj);
      }
      io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum other = (io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum) obj;

      if (corpus_ != other.corpus_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CORPUS_FIELD_NUMBER;
      hash = (53 * hash) + corpus_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.message.OneEnum}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.message.OneEnum)
        io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnumOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.edap.protobuf.test.message.v3.OneEnumOuterClass.internal_static_test_message_OneEnum_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.edap.protobuf.test.message.v3.OneEnumOuterClass.internal_static_test_message_OneEnum_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum.class, io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum.Builder.class);
      }

      // Construct using io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        corpus_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.edap.protobuf.test.message.v3.OneEnumOuterClass.internal_static_test_message_OneEnum_descriptor;
      }

      @java.lang.Override
      public io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum getDefaultInstanceForType() {
        return io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum.getDefaultInstance();
      }

      @java.lang.Override
      public io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum build() {
        io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum buildPartial() {
        io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum result = new io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum(this);
        result.corpus_ = corpus_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum) {
          return mergeFrom((io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum other) {
        if (other == io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum.getDefaultInstance()) return this;
        if (other.corpus_ != 0) {
          setCorpusValue(other.getCorpusValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int corpus_ = 0;
      /**
       * <code>.test.message.Corpus corpus = 1;</code>
       * @return The enum numeric value on the wire for corpus.
       */
      public int getCorpusValue() {
        return corpus_;
      }
      /**
       * <code>.test.message.Corpus corpus = 1;</code>
       * @param value The enum numeric value on the wire for corpus to set.
       * @return This builder for chaining.
       */
      public Builder setCorpusValue(int value) {
        corpus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.test.message.Corpus corpus = 1;</code>
       * @return The corpus.
       */
      public io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus getCorpus() {
        @SuppressWarnings("deprecation")
        io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus result = io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus.valueOf(corpus_);
        return result == null ? io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus.UNRECOGNIZED : result;
      }
      /**
       * <code>.test.message.Corpus corpus = 1;</code>
       * @param value The corpus to set.
       * @return This builder for chaining.
       */
      public Builder setCorpus(io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        corpus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.test.message.Corpus corpus = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCorpus() {
        
        corpus_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:test.message.OneEnum)
    }

    // @@protoc_insertion_point(class_scope:test.message.OneEnum)
    private static final io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum();
    }

    public static io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OneEnum>
        PARSER = new com.google.protobuf.AbstractParser<OneEnum>() {
      @java.lang.Override
      public OneEnum parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OneEnum(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OneEnum> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OneEnum> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.edap.protobuf.test.message.v3.OneEnumOuterClass.OneEnum getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_message_OneEnum_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_message_OneEnum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016one_enum.proto\022\014test.message\"/\n\007OneEnu" +
      "m\022$\n\006corpus\030\001 \001(\0162\024.test.message.Corpus*" +
      "Z\n\006Corpus\022\r\n\tUNIVERSAL\020\000\022\007\n\003WEB\020\001\022\n\n\006IMA" +
      "GES\020\002\022\t\n\005LOCAL\020\003\022\010\n\004NEWS\020\004\022\014\n\010PRODUCTS\020\005" +
      "\022\t\n\005VIDEO\020\006B\"\n io.edap.protobuf.test.mes" +
      "sage.v3b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_test_message_OneEnum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_message_OneEnum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_message_OneEnum_descriptor,
        new java.lang.String[] { "Corpus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
