<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.edap</groupId>
        <artifactId>edap</artifactId>
        <version>${edap.version}</version>
    </parent>

    <artifactId>edap-s3-parent</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>edap-s3-core</module>
        <module>edap-s3-server</module>
        <module>edap-s3-disk</module>
        <module>edap-s3-starter</module>
    </modules>

</project>
