// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all_type.proto

package io.edap.protobuf.test.message.v3;

public final class AllTypeOuterClass {
  private AllTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AllTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.message.AllType)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool field1 = 1;</code>
     * @return The field1.
     */
    boolean getField1();

    /**
     * <code>bytes field2 = 2;</code>
     * @return The field2.
     */
    com.google.protobuf.ByteString getField2();

    /**
     * <code>double field3 = 3;</code>
     * @return The field3.
     */
    double getField3();

    /**
     * <code>.test.message.Corpus field4 = 4;</code>
     * @return The enum numeric value on the wire for field4.
     */
    int getField4Value();
    /**
     * <code>.test.message.Corpus field4 = 4;</code>
     * @return The field4.
     */
    io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus getField4();

    /**
     * <code>fixed32 field5 = 5;</code>
     * @return The field5.
     */
    int getField5();

    /**
     * <code>fixed64 field6 = 6;</code>
     * @return The field6.
     */
    long getField6();

    /**
     * <code>float field7 = 7;</code>
     * @return The field7.
     */
    float getField7();

    /**
     * <code>int32 field8 = 8;</code>
     * @return The field8.
     */
    int getField8();

    /**
     * <code>int64 field9 = 9;</code>
     * @return The field9.
     */
    long getField9();

    /**
     * <code>map&lt;string, .test.message.Project&gt; field10 = 10;</code>
     */
    int getField10Count();
    /**
     * <code>map&lt;string, .test.message.Project&gt; field10 = 10;</code>
     */
    boolean containsField10(
        java.lang.String key);
    /**
     * Use {@link #getField10Map()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, io.edap.protobuf.test.message.v3.OneMapOuterClass.Project>
    getField10();
    /**
     * <code>map&lt;string, .test.message.Project&gt; field10 = 10;</code>
     */
    java.util.Map<java.lang.String, io.edap.protobuf.test.message.v3.OneMapOuterClass.Project>
    getField10Map();
    /**
     * <code>map&lt;string, .test.message.Project&gt; field10 = 10;</code>
     */

    io.edap.protobuf.test.message.v3.OneMapOuterClass.Project getField10OrDefault(
        java.lang.String key,
        io.edap.protobuf.test.message.v3.OneMapOuterClass.Project defaultValue);
    /**
     * <code>map&lt;string, .test.message.Project&gt; field10 = 10;</code>
     */

    io.edap.protobuf.test.message.v3.OneMapOuterClass.Project getField10OrThrow(
        java.lang.String key);

    /**
     * <code>.test.message.Proj field11 = 11;</code>
     * @return Whether the field11 field is set.
     */
    boolean hasField11();
    /**
     * <code>.test.message.Proj field11 = 11;</code>
     * @return The field11.
     */
    io.edap.protobuf.test.message.v3.OneMessageOuterClass.Proj getField11();
    /**
     * <code>.test.message.Proj field11 = 11;</code>
     */
    io.edap.protobuf.test.message.v3.OneMessageOuterClass.ProjOrBuilder getField11OrBuilder();

    /**
     * <code>sfixed32 field12 = 12;</code>
     * @return The field12.
     */
    int getField12();

    /**
     * <code>sfixed64 field13 = 13;</code>
     * @return The field13.
     */
    long getField13();

    /**
     * <code>sint32 field14 = 14;</code>
     * @return The field14.
     */
    int getField14();

    /**
     * <code>sint64 field15 = 15;</code>
     * @return The field15.
     */
    long getField15();

    /**
     * <code>string field16 = 16;</code>
     * @return The field16.
     */
    java.lang.String getField16();
    /**
     * <code>string field16 = 16;</code>
     * @return The bytes for field16.
     */
    com.google.protobuf.ByteString
        getField16Bytes();

    /**
     * <code>uint32 field17 = 17;</code>
     * @return The field17.
     */
    int getField17();

    /**
     * <code>uint64 field18 = 18;</code>
     * @return The field18.
     */
    long getField18();
  }
  /**
   * Protobuf type {@code test.message.AllType}
   */
  public  static final class AllType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:test.message.AllType)
      AllTypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AllType.newBuilder() to construct.
    private AllType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AllType() {
      field2_ = com.google.protobuf.ByteString.EMPTY;
      field4_ = 0;
      field16_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AllType();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AllType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              field1_ = input.readBool();
              break;
            }
            case 18: {

              field2_ = input.readBytes();
              break;
            }
            case 25: {

              field3_ = input.readDouble();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              field4_ = rawValue;
              break;
            }
            case 45: {

              field5_ = input.readFixed32();
              break;
            }
            case 49: {

              field6_ = input.readFixed64();
              break;
            }
            case 61: {

              field7_ = input.readFloat();
              break;
            }
            case 64: {

              field8_ = input.readInt32();
              break;
            }
            case 72: {

              field9_ = input.readInt64();
              break;
            }
            case 82: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                field10_ = com.google.protobuf.MapField.newMapField(
                    Field10DefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, io.edap.protobuf.test.message.v3.OneMapOuterClass.Project>
              field10__ = input.readMessage(
                  Field10DefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              field10_.getMutableMap().put(
                  field10__.getKey(), field10__.getValue());
              break;
            }
            case 90: {
              io.edap.protobuf.test.message.v3.OneMessageOuterClass.Proj.Builder subBuilder = null;
              if (field11_ != null) {
                subBuilder = field11_.toBuilder();
              }
              field11_ = input.readMessage(io.edap.protobuf.test.message.v3.OneMessageOuterClass.Proj.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(field11_);
                field11_ = subBuilder.buildPartial();
              }

              break;
            }
            case 101: {

              field12_ = input.readSFixed32();
              break;
            }
            case 105: {

              field13_ = input.readSFixed64();
              break;
            }
            case 112: {

              field14_ = input.readSInt32();
              break;
            }
            case 120: {

              field15_ = input.readSInt64();
              break;
            }
            case 130: {
              java.lang.String s = input.readStringRequireUtf8();

              field16_ = s;
              break;
            }
            case 136: {

              field17_ = input.readUInt32();
              break;
            }
            case 144: {

              field18_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.edap.protobuf.test.message.v3.AllTypeOuterClass.internal_static_test_message_AllType_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 10:
          return internalGetField10();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.edap.protobuf.test.message.v3.AllTypeOuterClass.internal_static_test_message_AllType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType.class, io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType.Builder.class);
    }

    public static final int FIELD1_FIELD_NUMBER = 1;
    private boolean field1_;
    /**
     * <code>bool field1 = 1;</code>
     * @return The field1.
     */
    public boolean getField1() {
      return field1_;
    }

    public static final int FIELD2_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString field2_;
    /**
     * <code>bytes field2 = 2;</code>
     * @return The field2.
     */
    public com.google.protobuf.ByteString getField2() {
      return field2_;
    }

    public static final int FIELD3_FIELD_NUMBER = 3;
    private double field3_;
    /**
     * <code>double field3 = 3;</code>
     * @return The field3.
     */
    public double getField3() {
      return field3_;
    }

    public static final int FIELD4_FIELD_NUMBER = 4;
    private int field4_;
    /**
     * <code>.test.message.Corpus field4 = 4;</code>
     * @return The enum numeric value on the wire for field4.
     */
    public int getField4Value() {
      return field4_;
    }
    /**
     * <code>.test.message.Corpus field4 = 4;</code>
     * @return The field4.
     */
    public io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus getField4() {
      @SuppressWarnings("deprecation")
      io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus result = io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus.valueOf(field4_);
      return result == null ? io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus.UNRECOGNIZED : result;
    }

    public static final int FIELD5_FIELD_NUMBER = 5;
    private int field5_;
    /**
     * <code>fixed32 field5 = 5;</code>
     * @return The field5.
     */
    public int getField5() {
      return field5_;
    }

    public static final int FIELD6_FIELD_NUMBER = 6;
    private long field6_;
    /**
     * <code>fixed64 field6 = 6;</code>
     * @return The field6.
     */
    public long getField6() {
      return field6_;
    }

    public static final int FIELD7_FIELD_NUMBER = 7;
    private float field7_;
    /**
     * <code>float field7 = 7;</code>
     * @return The field7.
     */
    public float getField7() {
      return field7_;
    }

    public static final int FIELD8_FIELD_NUMBER = 8;
    private int field8_;
    /**
     * <code>int32 field8 = 8;</code>
     * @return The field8.
     */
    public int getField8() {
      return field8_;
    }

    public static final int FIELD9_FIELD_NUMBER = 9;
    private long field9_;
    /**
     * <code>int64 field9 = 9;</code>
     * @return The field9.
     */
    public long getField9() {
      return field9_;
    }

    public static final int FIELD10_FIELD_NUMBER = 10;
    private static final class Field10DefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, io.edap.protobuf.test.message.v3.OneMapOuterClass.Project> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, io.edap.protobuf.test.message.v3.OneMapOuterClass.Project>newDefaultInstance(
                  io.edap.protobuf.test.message.v3.AllTypeOuterClass.internal_static_test_message_AllType_Field10Entry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  io.edap.protobuf.test.message.v3.OneMapOuterClass.Project.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, io.edap.protobuf.test.message.v3.OneMapOuterClass.Project> field10_;
    private com.google.protobuf.MapField<java.lang.String, io.edap.protobuf.test.message.v3.OneMapOuterClass.Project>
    internalGetField10() {
      if (field10_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            Field10DefaultEntryHolder.defaultEntry);
      }
      return field10_;
    }

    public int getField10Count() {
      return internalGetField10().getMap().size();
    }
    /**
     * <code>map&lt;string, .test.message.Project&gt; field10 = 10;</code>
     */

    public boolean containsField10(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetField10().getMap().containsKey(key);
    }
    /**
     * Use {@link #getField10Map()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.edap.protobuf.test.message.v3.OneMapOuterClass.Project> getField10() {
      return getField10Map();
    }
    /**
     * <code>map&lt;string, .test.message.Project&gt; field10 = 10;</code>
     */

    public java.util.Map<java.lang.String, io.edap.protobuf.test.message.v3.OneMapOuterClass.Project> getField10Map() {
      return internalGetField10().getMap();
    }
    /**
     * <code>map&lt;string, .test.message.Project&gt; field10 = 10;</code>
     */

    public io.edap.protobuf.test.message.v3.OneMapOuterClass.Project getField10OrDefault(
        java.lang.String key,
        io.edap.protobuf.test.message.v3.OneMapOuterClass.Project defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, io.edap.protobuf.test.message.v3.OneMapOuterClass.Project> map =
          internalGetField10().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .test.message.Project&gt; field10 = 10;</code>
     */

    public io.edap.protobuf.test.message.v3.OneMapOuterClass.Project getField10OrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, io.edap.protobuf.test.message.v3.OneMapOuterClass.Project> map =
          internalGetField10().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int FIELD11_FIELD_NUMBER = 11;
    private io.edap.protobuf.test.message.v3.OneMessageOuterClass.Proj field11_;
    /**
     * <code>.test.message.Proj field11 = 11;</code>
     * @return Whether the field11 field is set.
     */
    public boolean hasField11() {
      return field11_ != null;
    }
    /**
     * <code>.test.message.Proj field11 = 11;</code>
     * @return The field11.
     */
    public io.edap.protobuf.test.message.v3.OneMessageOuterClass.Proj getField11() {
      return field11_ == null ? io.edap.protobuf.test.message.v3.OneMessageOuterClass.Proj.getDefaultInstance() : field11_;
    }
    /**
     * <code>.test.message.Proj field11 = 11;</code>
     */
    public io.edap.protobuf.test.message.v3.OneMessageOuterClass.ProjOrBuilder getField11OrBuilder() {
      return getField11();
    }

    public static final int FIELD12_FIELD_NUMBER = 12;
    private int field12_;
    /**
     * <code>sfixed32 field12 = 12;</code>
     * @return The field12.
     */
    public int getField12() {
      return field12_;
    }

    public static final int FIELD13_FIELD_NUMBER = 13;
    private long field13_;
    /**
     * <code>sfixed64 field13 = 13;</code>
     * @return The field13.
     */
    public long getField13() {
      return field13_;
    }

    public static final int FIELD14_FIELD_NUMBER = 14;
    private int field14_;
    /**
     * <code>sint32 field14 = 14;</code>
     * @return The field14.
     */
    public int getField14() {
      return field14_;
    }

    public static final int FIELD15_FIELD_NUMBER = 15;
    private long field15_;
    /**
     * <code>sint64 field15 = 15;</code>
     * @return The field15.
     */
    public long getField15() {
      return field15_;
    }

    public static final int FIELD16_FIELD_NUMBER = 16;
    private volatile java.lang.Object field16_;
    /**
     * <code>string field16 = 16;</code>
     * @return The field16.
     */
    public java.lang.String getField16() {
      java.lang.Object ref = field16_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field16_ = s;
        return s;
      }
    }
    /**
     * <code>string field16 = 16;</code>
     * @return The bytes for field16.
     */
    public com.google.protobuf.ByteString
        getField16Bytes() {
      java.lang.Object ref = field16_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field16_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIELD17_FIELD_NUMBER = 17;
    private int field17_;
    /**
     * <code>uint32 field17 = 17;</code>
     * @return The field17.
     */
    public int getField17() {
      return field17_;
    }

    public static final int FIELD18_FIELD_NUMBER = 18;
    private long field18_;
    /**
     * <code>uint64 field18 = 18;</code>
     * @return The field18.
     */
    public long getField18() {
      return field18_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (field1_ != false) {
        output.writeBool(1, field1_);
      }
      if (!field2_.isEmpty()) {
        output.writeBytes(2, field2_);
      }
      if (field3_ != 0D) {
        output.writeDouble(3, field3_);
      }
      if (field4_ != io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus.UNIVERSAL.getNumber()) {
        output.writeEnum(4, field4_);
      }
      if (field5_ != 0) {
        output.writeFixed32(5, field5_);
      }
      if (field6_ != 0L) {
        output.writeFixed64(6, field6_);
      }
      if (field7_ != 0F) {
        output.writeFloat(7, field7_);
      }
      if (field8_ != 0) {
        output.writeInt32(8, field8_);
      }
      if (field9_ != 0L) {
        output.writeInt64(9, field9_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetField10(),
          Field10DefaultEntryHolder.defaultEntry,
          10);
      if (field11_ != null) {
        output.writeMessage(11, getField11());
      }
      if (field12_ != 0) {
        output.writeSFixed32(12, field12_);
      }
      if (field13_ != 0L) {
        output.writeSFixed64(13, field13_);
      }
      if (field14_ != 0) {
        output.writeSInt32(14, field14_);
      }
      if (field15_ != 0L) {
        output.writeSInt64(15, field15_);
      }
      if (!getField16Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 16, field16_);
      }
      if (field17_ != 0) {
        output.writeUInt32(17, field17_);
      }
      if (field18_ != 0L) {
        output.writeUInt64(18, field18_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (field1_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, field1_);
      }
      if (!field2_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, field2_);
      }
      if (field3_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, field3_);
      }
      if (field4_ != io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus.UNIVERSAL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, field4_);
      }
      if (field5_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(5, field5_);
      }
      if (field6_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(6, field6_);
      }
      if (field7_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, field7_);
      }
      if (field8_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, field8_);
      }
      if (field9_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, field9_);
      }
      for (java.util.Map.Entry<java.lang.String, io.edap.protobuf.test.message.v3.OneMapOuterClass.Project> entry
           : internalGetField10().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, io.edap.protobuf.test.message.v3.OneMapOuterClass.Project>
        field10__ = Field10DefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(10, field10__);
      }
      if (field11_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, getField11());
      }
      if (field12_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed32Size(12, field12_);
      }
      if (field13_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed64Size(13, field13_);
      }
      if (field14_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(14, field14_);
      }
      if (field15_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(15, field15_);
      }
      if (!getField16Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, field16_);
      }
      if (field17_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(17, field17_);
      }
      if (field18_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(18, field18_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType)) {
        return super.equals(obj);
      }
      io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType other = (io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType) obj;

      if (getField1()
          != other.getField1()) return false;
      if (!getField2()
          .equals(other.getField2())) return false;
      if (java.lang.Double.doubleToLongBits(getField3())
          != java.lang.Double.doubleToLongBits(
              other.getField3())) return false;
      if (field4_ != other.field4_) return false;
      if (getField5()
          != other.getField5()) return false;
      if (getField6()
          != other.getField6()) return false;
      if (java.lang.Float.floatToIntBits(getField7())
          != java.lang.Float.floatToIntBits(
              other.getField7())) return false;
      if (getField8()
          != other.getField8()) return false;
      if (getField9()
          != other.getField9()) return false;
      if (!internalGetField10().equals(
          other.internalGetField10())) return false;
      if (hasField11() != other.hasField11()) return false;
      if (hasField11()) {
        if (!getField11()
            .equals(other.getField11())) return false;
      }
      if (getField12()
          != other.getField12()) return false;
      if (getField13()
          != other.getField13()) return false;
      if (getField14()
          != other.getField14()) return false;
      if (getField15()
          != other.getField15()) return false;
      if (!getField16()
          .equals(other.getField16())) return false;
      if (getField17()
          != other.getField17()) return false;
      if (getField18()
          != other.getField18()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIELD1_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getField1());
      hash = (37 * hash) + FIELD2_FIELD_NUMBER;
      hash = (53 * hash) + getField2().hashCode();
      hash = (37 * hash) + FIELD3_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getField3()));
      hash = (37 * hash) + FIELD4_FIELD_NUMBER;
      hash = (53 * hash) + field4_;
      hash = (37 * hash) + FIELD5_FIELD_NUMBER;
      hash = (53 * hash) + getField5();
      hash = (37 * hash) + FIELD6_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getField6());
      hash = (37 * hash) + FIELD7_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getField7());
      hash = (37 * hash) + FIELD8_FIELD_NUMBER;
      hash = (53 * hash) + getField8();
      hash = (37 * hash) + FIELD9_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getField9());
      if (!internalGetField10().getMap().isEmpty()) {
        hash = (37 * hash) + FIELD10_FIELD_NUMBER;
        hash = (53 * hash) + internalGetField10().hashCode();
      }
      if (hasField11()) {
        hash = (37 * hash) + FIELD11_FIELD_NUMBER;
        hash = (53 * hash) + getField11().hashCode();
      }
      hash = (37 * hash) + FIELD12_FIELD_NUMBER;
      hash = (53 * hash) + getField12();
      hash = (37 * hash) + FIELD13_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getField13());
      hash = (37 * hash) + FIELD14_FIELD_NUMBER;
      hash = (53 * hash) + getField14();
      hash = (37 * hash) + FIELD15_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getField15());
      hash = (37 * hash) + FIELD16_FIELD_NUMBER;
      hash = (53 * hash) + getField16().hashCode();
      hash = (37 * hash) + FIELD17_FIELD_NUMBER;
      hash = (53 * hash) + getField17();
      hash = (37 * hash) + FIELD18_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getField18());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.message.AllType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.message.AllType)
        io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.edap.protobuf.test.message.v3.AllTypeOuterClass.internal_static_test_message_AllType_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 10:
            return internalGetField10();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 10:
            return internalGetMutableField10();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.edap.protobuf.test.message.v3.AllTypeOuterClass.internal_static_test_message_AllType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType.class, io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType.Builder.class);
      }

      // Construct using io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        field1_ = false;

        field2_ = com.google.protobuf.ByteString.EMPTY;

        field3_ = 0D;

        field4_ = 0;

        field5_ = 0;

        field6_ = 0L;

        field7_ = 0F;

        field8_ = 0;

        field9_ = 0L;

        internalGetMutableField10().clear();
        if (field11Builder_ == null) {
          field11_ = null;
        } else {
          field11_ = null;
          field11Builder_ = null;
        }
        field12_ = 0;

        field13_ = 0L;

        field14_ = 0;

        field15_ = 0L;

        field16_ = "";

        field17_ = 0;

        field18_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.edap.protobuf.test.message.v3.AllTypeOuterClass.internal_static_test_message_AllType_descriptor;
      }

      @java.lang.Override
      public io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType getDefaultInstanceForType() {
        return io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType.getDefaultInstance();
      }

      @java.lang.Override
      public io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType build() {
        io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType buildPartial() {
        io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType result = new io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType(this);
        int from_bitField0_ = bitField0_;
        result.field1_ = field1_;
        result.field2_ = field2_;
        result.field3_ = field3_;
        result.field4_ = field4_;
        result.field5_ = field5_;
        result.field6_ = field6_;
        result.field7_ = field7_;
        result.field8_ = field8_;
        result.field9_ = field9_;
        result.field10_ = internalGetField10();
        result.field10_.makeImmutable();
        if (field11Builder_ == null) {
          result.field11_ = field11_;
        } else {
          result.field11_ = field11Builder_.build();
        }
        result.field12_ = field12_;
        result.field13_ = field13_;
        result.field14_ = field14_;
        result.field15_ = field15_;
        result.field16_ = field16_;
        result.field17_ = field17_;
        result.field18_ = field18_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType) {
          return mergeFrom((io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType other) {
        if (other == io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType.getDefaultInstance()) return this;
        if (other.getField1() != false) {
          setField1(other.getField1());
        }
        if (other.getField2() != com.google.protobuf.ByteString.EMPTY) {
          setField2(other.getField2());
        }
        if (other.getField3() != 0D) {
          setField3(other.getField3());
        }
        if (other.field4_ != 0) {
          setField4Value(other.getField4Value());
        }
        if (other.getField5() != 0) {
          setField5(other.getField5());
        }
        if (other.getField6() != 0L) {
          setField6(other.getField6());
        }
        if (other.getField7() != 0F) {
          setField7(other.getField7());
        }
        if (other.getField8() != 0) {
          setField8(other.getField8());
        }
        if (other.getField9() != 0L) {
          setField9(other.getField9());
        }
        internalGetMutableField10().mergeFrom(
            other.internalGetField10());
        if (other.hasField11()) {
          mergeField11(other.getField11());
        }
        if (other.getField12() != 0) {
          setField12(other.getField12());
        }
        if (other.getField13() != 0L) {
          setField13(other.getField13());
        }
        if (other.getField14() != 0) {
          setField14(other.getField14());
        }
        if (other.getField15() != 0L) {
          setField15(other.getField15());
        }
        if (!other.getField16().isEmpty()) {
          field16_ = other.field16_;
          onChanged();
        }
        if (other.getField17() != 0) {
          setField17(other.getField17());
        }
        if (other.getField18() != 0L) {
          setField18(other.getField18());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean field1_ ;
      /**
       * <code>bool field1 = 1;</code>
       * @return The field1.
       */
      public boolean getField1() {
        return field1_;
      }
      /**
       * <code>bool field1 = 1;</code>
       * @param value The field1 to set.
       * @return This builder for chaining.
       */
      public Builder setField1(boolean value) {
        
        field1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool field1 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearField1() {
        
        field1_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString field2_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes field2 = 2;</code>
       * @return The field2.
       */
      public com.google.protobuf.ByteString getField2() {
        return field2_;
      }
      /**
       * <code>bytes field2 = 2;</code>
       * @param value The field2 to set.
       * @return This builder for chaining.
       */
      public Builder setField2(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        field2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes field2 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearField2() {
        
        field2_ = getDefaultInstance().getField2();
        onChanged();
        return this;
      }

      private double field3_ ;
      /**
       * <code>double field3 = 3;</code>
       * @return The field3.
       */
      public double getField3() {
        return field3_;
      }
      /**
       * <code>double field3 = 3;</code>
       * @param value The field3 to set.
       * @return This builder for chaining.
       */
      public Builder setField3(double value) {
        
        field3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double field3 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearField3() {
        
        field3_ = 0D;
        onChanged();
        return this;
      }

      private int field4_ = 0;
      /**
       * <code>.test.message.Corpus field4 = 4;</code>
       * @return The enum numeric value on the wire for field4.
       */
      public int getField4Value() {
        return field4_;
      }
      /**
       * <code>.test.message.Corpus field4 = 4;</code>
       * @param value The enum numeric value on the wire for field4 to set.
       * @return This builder for chaining.
       */
      public Builder setField4Value(int value) {
        field4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.test.message.Corpus field4 = 4;</code>
       * @return The field4.
       */
      public io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus getField4() {
        @SuppressWarnings("deprecation")
        io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus result = io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus.valueOf(field4_);
        return result == null ? io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus.UNRECOGNIZED : result;
      }
      /**
       * <code>.test.message.Corpus field4 = 4;</code>
       * @param value The field4 to set.
       * @return This builder for chaining.
       */
      public Builder setField4(io.edap.protobuf.test.message.v3.OneEnumOuterClass.Corpus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        field4_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.test.message.Corpus field4 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearField4() {
        
        field4_ = 0;
        onChanged();
        return this;
      }

      private int field5_ ;
      /**
       * <code>fixed32 field5 = 5;</code>
       * @return The field5.
       */
      public int getField5() {
        return field5_;
      }
      /**
       * <code>fixed32 field5 = 5;</code>
       * @param value The field5 to set.
       * @return This builder for chaining.
       */
      public Builder setField5(int value) {
        
        field5_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed32 field5 = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearField5() {
        
        field5_ = 0;
        onChanged();
        return this;
      }

      private long field6_ ;
      /**
       * <code>fixed64 field6 = 6;</code>
       * @return The field6.
       */
      public long getField6() {
        return field6_;
      }
      /**
       * <code>fixed64 field6 = 6;</code>
       * @param value The field6 to set.
       * @return This builder for chaining.
       */
      public Builder setField6(long value) {
        
        field6_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed64 field6 = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearField6() {
        
        field6_ = 0L;
        onChanged();
        return this;
      }

      private float field7_ ;
      /**
       * <code>float field7 = 7;</code>
       * @return The field7.
       */
      public float getField7() {
        return field7_;
      }
      /**
       * <code>float field7 = 7;</code>
       * @param value The field7 to set.
       * @return This builder for chaining.
       */
      public Builder setField7(float value) {
        
        field7_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float field7 = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearField7() {
        
        field7_ = 0F;
        onChanged();
        return this;
      }

      private int field8_ ;
      /**
       * <code>int32 field8 = 8;</code>
       * @return The field8.
       */
      public int getField8() {
        return field8_;
      }
      /**
       * <code>int32 field8 = 8;</code>
       * @param value The field8 to set.
       * @return This builder for chaining.
       */
      public Builder setField8(int value) {
        
        field8_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 field8 = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearField8() {
        
        field8_ = 0;
        onChanged();
        return this;
      }

      private long field9_ ;
      /**
       * <code>int64 field9 = 9;</code>
       * @return The field9.
       */
      public long getField9() {
        return field9_;
      }
      /**
       * <code>int64 field9 = 9;</code>
       * @param value The field9 to set.
       * @return This builder for chaining.
       */
      public Builder setField9(long value) {
        
        field9_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 field9 = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearField9() {
        
        field9_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, io.edap.protobuf.test.message.v3.OneMapOuterClass.Project> field10_;
      private com.google.protobuf.MapField<java.lang.String, io.edap.protobuf.test.message.v3.OneMapOuterClass.Project>
      internalGetField10() {
        if (field10_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              Field10DefaultEntryHolder.defaultEntry);
        }
        return field10_;
      }
      private com.google.protobuf.MapField<java.lang.String, io.edap.protobuf.test.message.v3.OneMapOuterClass.Project>
      internalGetMutableField10() {
        onChanged();;
        if (field10_ == null) {
          field10_ = com.google.protobuf.MapField.newMapField(
              Field10DefaultEntryHolder.defaultEntry);
        }
        if (!field10_.isMutable()) {
          field10_ = field10_.copy();
        }
        return field10_;
      }

      public int getField10Count() {
        return internalGetField10().getMap().size();
      }
      /**
       * <code>map&lt;string, .test.message.Project&gt; field10 = 10;</code>
       */

      public boolean containsField10(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetField10().getMap().containsKey(key);
      }
      /**
       * Use {@link #getField10Map()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, io.edap.protobuf.test.message.v3.OneMapOuterClass.Project> getField10() {
        return getField10Map();
      }
      /**
       * <code>map&lt;string, .test.message.Project&gt; field10 = 10;</code>
       */

      public java.util.Map<java.lang.String, io.edap.protobuf.test.message.v3.OneMapOuterClass.Project> getField10Map() {
        return internalGetField10().getMap();
      }
      /**
       * <code>map&lt;string, .test.message.Project&gt; field10 = 10;</code>
       */

      public io.edap.protobuf.test.message.v3.OneMapOuterClass.Project getField10OrDefault(
          java.lang.String key,
          io.edap.protobuf.test.message.v3.OneMapOuterClass.Project defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, io.edap.protobuf.test.message.v3.OneMapOuterClass.Project> map =
            internalGetField10().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .test.message.Project&gt; field10 = 10;</code>
       */

      public io.edap.protobuf.test.message.v3.OneMapOuterClass.Project getField10OrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, io.edap.protobuf.test.message.v3.OneMapOuterClass.Project> map =
            internalGetField10().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearField10() {
        internalGetMutableField10().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .test.message.Project&gt; field10 = 10;</code>
       */

      public Builder removeField10(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableField10().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, io.edap.protobuf.test.message.v3.OneMapOuterClass.Project>
      getMutableField10() {
        return internalGetMutableField10().getMutableMap();
      }
      /**
       * <code>map&lt;string, .test.message.Project&gt; field10 = 10;</code>
       */
      public Builder putField10(
          java.lang.String key,
          io.edap.protobuf.test.message.v3.OneMapOuterClass.Project value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableField10().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .test.message.Project&gt; field10 = 10;</code>
       */

      public Builder putAllField10(
          java.util.Map<java.lang.String, io.edap.protobuf.test.message.v3.OneMapOuterClass.Project> values) {
        internalGetMutableField10().getMutableMap()
            .putAll(values);
        return this;
      }

      private io.edap.protobuf.test.message.v3.OneMessageOuterClass.Proj field11_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.edap.protobuf.test.message.v3.OneMessageOuterClass.Proj, io.edap.protobuf.test.message.v3.OneMessageOuterClass.Proj.Builder, io.edap.protobuf.test.message.v3.OneMessageOuterClass.ProjOrBuilder> field11Builder_;
      /**
       * <code>.test.message.Proj field11 = 11;</code>
       * @return Whether the field11 field is set.
       */
      public boolean hasField11() {
        return field11Builder_ != null || field11_ != null;
      }
      /**
       * <code>.test.message.Proj field11 = 11;</code>
       * @return The field11.
       */
      public io.edap.protobuf.test.message.v3.OneMessageOuterClass.Proj getField11() {
        if (field11Builder_ == null) {
          return field11_ == null ? io.edap.protobuf.test.message.v3.OneMessageOuterClass.Proj.getDefaultInstance() : field11_;
        } else {
          return field11Builder_.getMessage();
        }
      }
      /**
       * <code>.test.message.Proj field11 = 11;</code>
       */
      public Builder setField11(io.edap.protobuf.test.message.v3.OneMessageOuterClass.Proj value) {
        if (field11Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          field11_ = value;
          onChanged();
        } else {
          field11Builder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.test.message.Proj field11 = 11;</code>
       */
      public Builder setField11(
          io.edap.protobuf.test.message.v3.OneMessageOuterClass.Proj.Builder builderForValue) {
        if (field11Builder_ == null) {
          field11_ = builderForValue.build();
          onChanged();
        } else {
          field11Builder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.test.message.Proj field11 = 11;</code>
       */
      public Builder mergeField11(io.edap.protobuf.test.message.v3.OneMessageOuterClass.Proj value) {
        if (field11Builder_ == null) {
          if (field11_ != null) {
            field11_ =
              io.edap.protobuf.test.message.v3.OneMessageOuterClass.Proj.newBuilder(field11_).mergeFrom(value).buildPartial();
          } else {
            field11_ = value;
          }
          onChanged();
        } else {
          field11Builder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.test.message.Proj field11 = 11;</code>
       */
      public Builder clearField11() {
        if (field11Builder_ == null) {
          field11_ = null;
          onChanged();
        } else {
          field11_ = null;
          field11Builder_ = null;
        }

        return this;
      }
      /**
       * <code>.test.message.Proj field11 = 11;</code>
       */
      public io.edap.protobuf.test.message.v3.OneMessageOuterClass.Proj.Builder getField11Builder() {
        
        onChanged();
        return getField11FieldBuilder().getBuilder();
      }
      /**
       * <code>.test.message.Proj field11 = 11;</code>
       */
      public io.edap.protobuf.test.message.v3.OneMessageOuterClass.ProjOrBuilder getField11OrBuilder() {
        if (field11Builder_ != null) {
          return field11Builder_.getMessageOrBuilder();
        } else {
          return field11_ == null ?
              io.edap.protobuf.test.message.v3.OneMessageOuterClass.Proj.getDefaultInstance() : field11_;
        }
      }
      /**
       * <code>.test.message.Proj field11 = 11;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.edap.protobuf.test.message.v3.OneMessageOuterClass.Proj, io.edap.protobuf.test.message.v3.OneMessageOuterClass.Proj.Builder, io.edap.protobuf.test.message.v3.OneMessageOuterClass.ProjOrBuilder> 
          getField11FieldBuilder() {
        if (field11Builder_ == null) {
          field11Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.edap.protobuf.test.message.v3.OneMessageOuterClass.Proj, io.edap.protobuf.test.message.v3.OneMessageOuterClass.Proj.Builder, io.edap.protobuf.test.message.v3.OneMessageOuterClass.ProjOrBuilder>(
                  getField11(),
                  getParentForChildren(),
                  isClean());
          field11_ = null;
        }
        return field11Builder_;
      }

      private int field12_ ;
      /**
       * <code>sfixed32 field12 = 12;</code>
       * @return The field12.
       */
      public int getField12() {
        return field12_;
      }
      /**
       * <code>sfixed32 field12 = 12;</code>
       * @param value The field12 to set.
       * @return This builder for chaining.
       */
      public Builder setField12(int value) {
        
        field12_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sfixed32 field12 = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearField12() {
        
        field12_ = 0;
        onChanged();
        return this;
      }

      private long field13_ ;
      /**
       * <code>sfixed64 field13 = 13;</code>
       * @return The field13.
       */
      public long getField13() {
        return field13_;
      }
      /**
       * <code>sfixed64 field13 = 13;</code>
       * @param value The field13 to set.
       * @return This builder for chaining.
       */
      public Builder setField13(long value) {
        
        field13_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sfixed64 field13 = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearField13() {
        
        field13_ = 0L;
        onChanged();
        return this;
      }

      private int field14_ ;
      /**
       * <code>sint32 field14 = 14;</code>
       * @return The field14.
       */
      public int getField14() {
        return field14_;
      }
      /**
       * <code>sint32 field14 = 14;</code>
       * @param value The field14 to set.
       * @return This builder for chaining.
       */
      public Builder setField14(int value) {
        
        field14_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 field14 = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearField14() {
        
        field14_ = 0;
        onChanged();
        return this;
      }

      private long field15_ ;
      /**
       * <code>sint64 field15 = 15;</code>
       * @return The field15.
       */
      public long getField15() {
        return field15_;
      }
      /**
       * <code>sint64 field15 = 15;</code>
       * @param value The field15 to set.
       * @return This builder for chaining.
       */
      public Builder setField15(long value) {
        
        field15_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 field15 = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearField15() {
        
        field15_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object field16_ = "";
      /**
       * <code>string field16 = 16;</code>
       * @return The field16.
       */
      public java.lang.String getField16() {
        java.lang.Object ref = field16_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          field16_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string field16 = 16;</code>
       * @return The bytes for field16.
       */
      public com.google.protobuf.ByteString
          getField16Bytes() {
        java.lang.Object ref = field16_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          field16_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string field16 = 16;</code>
       * @param value The field16 to set.
       * @return This builder for chaining.
       */
      public Builder setField16(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        field16_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string field16 = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearField16() {
        
        field16_ = getDefaultInstance().getField16();
        onChanged();
        return this;
      }
      /**
       * <code>string field16 = 16;</code>
       * @param value The bytes for field16 to set.
       * @return This builder for chaining.
       */
      public Builder setField16Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        field16_ = value;
        onChanged();
        return this;
      }

      private int field17_ ;
      /**
       * <code>uint32 field17 = 17;</code>
       * @return The field17.
       */
      public int getField17() {
        return field17_;
      }
      /**
       * <code>uint32 field17 = 17;</code>
       * @param value The field17 to set.
       * @return This builder for chaining.
       */
      public Builder setField17(int value) {
        
        field17_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 field17 = 17;</code>
       * @return This builder for chaining.
       */
      public Builder clearField17() {
        
        field17_ = 0;
        onChanged();
        return this;
      }

      private long field18_ ;
      /**
       * <code>uint64 field18 = 18;</code>
       * @return The field18.
       */
      public long getField18() {
        return field18_;
      }
      /**
       * <code>uint64 field18 = 18;</code>
       * @param value The field18 to set.
       * @return This builder for chaining.
       */
      public Builder setField18(long value) {
        
        field18_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 field18 = 18;</code>
       * @return This builder for chaining.
       */
      public Builder clearField18() {
        
        field18_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:test.message.AllType)
    }

    // @@protoc_insertion_point(class_scope:test.message.AllType)
    private static final io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType();
    }

    public static io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AllType>
        PARSER = new com.google.protobuf.AbstractParser<AllType>() {
      @java.lang.Override
      public AllType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AllType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AllType> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AllType> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.edap.protobuf.test.message.v3.AllTypeOuterClass.AllType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_message_AllType_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_message_AllType_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_message_AllType_Field10Entry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_message_AllType_Field10Entry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016all_type.proto\022\014test.message\032\016one_enum" +
      ".proto\032\rone_map.proto\032\021one_message.proto" +
      "\"\307\003\n\007AllType\022\016\n\006field1\030\001 \001(\010\022\016\n\006field2\030\002" +
      " \001(\014\022\016\n\006field3\030\003 \001(\001\022$\n\006field4\030\004 \001(\0162\024.t" +
      "est.message.Corpus\022\016\n\006field5\030\005 \001(\007\022\016\n\006fi" +
      "eld6\030\006 \001(\006\022\016\n\006field7\030\007 \001(\002\022\016\n\006field8\030\010 \001" +
      "(\005\022\016\n\006field9\030\t \001(\003\0223\n\007field10\030\n \003(\0132\".te" +
      "st.message.AllType.Field10Entry\022#\n\007field" +
      "11\030\013 \001(\0132\022.test.message.Proj\022\017\n\007field12\030" +
      "\014 \001(\017\022\017\n\007field13\030\r \001(\020\022\017\n\007field14\030\016 \001(\021\022" +
      "\017\n\007field15\030\017 \001(\022\022\017\n\007field16\030\020 \001(\t\022\017\n\007fie" +
      "ld17\030\021 \001(\r\022\017\n\007field18\030\022 \001(\004\032E\n\014Field10En" +
      "try\022\013\n\003key\030\001 \001(\t\022$\n\005value\030\002 \001(\0132\025.test.m" +
      "essage.Project:\0028\001B\"\n io.edap.protobuf.t" +
      "est.message.v3b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.edap.protobuf.test.message.v3.OneEnumOuterClass.getDescriptor(),
          io.edap.protobuf.test.message.v3.OneMapOuterClass.getDescriptor(),
          io.edap.protobuf.test.message.v3.OneMessageOuterClass.getDescriptor(),
        });
    internal_static_test_message_AllType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_message_AllType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_message_AllType_descriptor,
        new java.lang.String[] { "Field1", "Field2", "Field3", "Field4", "Field5", "Field6", "Field7", "Field8", "Field9", "Field10", "Field11", "Field12", "Field13", "Field14", "Field15", "Field16", "Field17", "Field18", });
    internal_static_test_message_AllType_Field10Entry_descriptor =
      internal_static_test_message_AllType_descriptor.getNestedTypes().get(0);
    internal_static_test_message_AllType_Field10Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_message_AllType_Field10Entry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    io.edap.protobuf.test.message.v3.OneEnumOuterClass.getDescriptor();
    io.edap.protobuf.test.message.v3.OneMapOuterClass.getDescriptor();
    io.edap.protobuf.test.message.v3.OneMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
